module.exports = {
   "abap":".abap",
   "antlr":".g4",
   "asp":".asp",
   "ats":".dats",
   "actionscript":".as",
   "ada":".adb",
   "agda":".agda",
   "apacheconf":".apacheconf",
   "apex":".cls",
   "applescript":".applescript",
   "arc":".arc",
   "arduino":".ino",
   "asciidoc":".asciidoc",
   "assembly":".asm",
   "augeas":".aug",
   "autohotkey":".ahk",
   "autoit":".au3",
   "awk":".awk",
   "batchfile":".bat",
   "befunge":".befunge",
   "blitzbasic":".bb",
   "blitzmax":".bmx",
   "bluespec":".bsv",
   "boo":".boo",
   "brainfuck":".b",
   "brightscript":".brs",
   "bro":".bro",
   "c":".c",
   "c#":".cs",
   "c++":".cpp",
   "c-objdump":".c-objdump",
   "c2hs haskell":".chs",
   "clips":".clp",
   "cmake":".cmake",
   "cobol":".cob",
   "css":".css",
   "ceylon":".ceylon",
   "chuck":".ck",
   "cirru":".cirru",
   "clean":".icl",
   "clojure":".clj",
   "coffeescript":".coffee",
   "coldfusion":".cfm",
   "common lisp":".lisp",
   "coq":".coq",
   "cpp-objdump":".cppobjdump",
   "creole":".creole",
   "crystal":".cr",
   "cucumber":".feature",
   "cuda":".cu",
   "cython":".pyx",
   "d":".d",
   "d-objdump":".d-objdump",
   "dm":".dm",
   "dot":".dot",
   "darcs patch":".darcspatch",
   "dart":".dart",
   "dcpu-16 asm":".dasm16",
   "diff":".diff",
   "dylan":".dylan",
   "ecere projects":".epj",
   "ecl":".ecl",
   "eiffel":".e",
   "elixir":".ex",
   "elm":".elm",
   "emacs lisp":".el",
   "erlang":".erl",
   "f#":".fs",
   "flux":".fx",
   "fortran":".f90",
   "factor":".factor",
   "fancy":".fy",
   "fantom":".fan",
   "forth":".fth",
   "gas":".s",
   "glsl":".glsl",
   "genshi":".kid",
   "gentoo ebuild":".ebuild",
   "gentoo eclass":".eclass",
   "gettext catalog":".po",
   "glyph":".glf",
   "go":".go",
   "gosu":".gs",
   "groff":".man",
   "groovy":".groovy",
   "groovy server pages":".gsp",
   "html":".html",
   "html+django":".mustache",
   "html+erb":".erb",
   "html+php":".phtml",
   "http":".http",
   "haml":".haml",
   "handlebars":".handlebars",
   "harbour":".hb",
   "haskell":".hs",
   "haxe":".hx",
   "hy":".hy",
   "idl":".pro",
   "ini":".ini",
   "idris":".idr",
   "inno setup":".iss",
   "irc log":".irclog",
   "io":".io",
   "ioke":".ik",
   "j":".ijs",
   "json":".json",
   "json5":".json5",
   "jsonld":".jsonld",
   "jade":".jade",
   "java":".java",
   "java server pages":".jsp",
   "javascript":".js",
   "julia":".jl",
   "krl":".krl",
   "kotlin":".kt",
   "lfe":".lfe",
   "llvm":".ll",
   "lasso":".lasso",
   "less":".less",
   "lilypond":".ly",
   "literate agda":".lagda",
   "literate coffeescript":".litcoffee",
   "literate haskell":".lhs",
   "livescript":".ls",
   "logos":".xm",
   "logtalk":".lgt",
   "lua":".lua",
   "m":".mumps",
   "makefile":".mak",
   "mako":".mako",
   "markdown":".md",
   "mask":".mask",
   "matlab":".matlab",
   "max":".maxpat",
   "mediawiki":".mediawiki",
   "minid":".minid",
   "mirah":".druby",
   "monkey":".monkey",
   "moocode":".moo",
   "moonscript":".moon",
   "myghty":".myt",
   "nsis":".nsi",
   "nemerle":".n",
   "netlogo":".nlogo",
   "nginx":".nginxconf",
   "nimrod":".nim",
   "nu":".nu",
   "numpy":".numpy",
   "ocaml":".ml",
   "objdump":".objdump",
   "objective-c":".m",
   "objective-j":".j",
   "omgrofl":".omgrofl",
   "opa":".opa",
   "opencl":".cl",
   "openedge abl":".p",
   "org":".org",
   "oxygene":".oxygene",
   "pawn":".pwn",
   "php":".php",
   "parrot":".parrot",
   "parrot internal representation":".pir",
   "parrot assembly":".pasm",
   "pascal":".pas",
   "perl":".pl",
   "perl6":".p6",
   "pike":".pike",
   "pod":".pod",
   "pogoscript":".pogo",
   "postscript":".ps",
   "powershell":".ps1",
   "processing":".pde",
   "prolog":".prolog",
   "protocol buffer":".proto",
   "puppet":".pp",
   "pure data":".pd",
   "python":".py",
   "python traceback":".pytb",
   "qml":".qml",
   "r":".r",
   "rdoc":".rdoc",
   "realbasic":".rbbas",
   "rhtml":".rhtml",
   "rmarkdown":".rmd",
   "racket":".rkt",
   "ragel in ruby host":".rl",
   "raw token data":".raw",
   "rebol":".rebol",
   "redcode":".cw",
   "robotframework":".robot",
   "rouge":".rg",
   "ruby":".rb",
   "rust":".rs",
   "scss":".scss",
   "sql":".sql",
   "sage":".sage",
   "sass":".sass",
   "scala":".scala",
   "scaml":".scaml",
   "scheme":".scm",
   "scilab":".sci",
   "self":".self",
   "shell":".sh",
   "shen":".shen",
   "slash":".sl",
   "smalltalk":".st",
   "smarty":".tpl",
   "squirrel":".nut",
   "standard ml":".sml",
   "stylus":".styl",
   "supercollider":".scd",
   "toml":".toml",
   "txl":".txl",
   "tcl":".tcl",
   "tcsh":".tcsh",
   "tex":".tex",
   "tea":".tea",
   "textile":".textile",
   "turing":".t",
   "twig":".twig",
   "typescript":".ts",
   "unified parallel c":".upc",
   "unrealscript":".uc",
   "vhdl":".vhdl",
   "vala":".vala",
   "verilog":".v",
   "viml":".vim",
   "visual basic":".vb",
   "volt":".volt",
   "xc":".xc",
   "xml":".xml",
   "xproc":".xpl",
   "xquery":".xquery",
   "xs":".xs",
   "xslt":".xslt",
   "xtend":".xtend",
   "yaml":".yml",
   "ec":".ec",
   "edn":".edn",
   "fish":".fish",
   "mupad":".mu",
   "nesc":".nc",
   "ooc":".ooc",
   "restructuredtext":".rst",
   "wisp":".wisp",
   "xbase":".prg"
}
