#!/usr/bin/env node
var fs = require("fs"),
    _ = require("underscore"),
    utils = require("./src/node-utils.js"),
    literate = require('./src/literate.js'),
    argv = require("minimist")(process.argv.slice(2)),
    filename = argv._[0] || ".",
    watch = argv.w,
    output = argv.o,
    templatePath = argv.t || "./src/templates/markdown-template.html",
    renderFunc = require("./src/markdownRender.js");

utils.read(templatePath).then(function(template) {
  var legacy = function(path, output) {
    utils.read(path).then(function(file) {
      var fileName = _.last(path.split("/"));
      var blocks = literate(file, fileName, null, "markdown");
      
      var rendered = renderFunc(blocks, template);
      if(output) {
        utils.write(output, rendered);
      } else {
        console.log(rendered);
      }
   });
  };

  if(fs.lstatSync(filename).isDirectory()) {
    if(!output) {
      output = ".";
    }
    if(!/\/$/.test(output)) {
      output += "/";
    }
    utils.walk(filename).then(function(results) {
      results.forEach(function(path) {
        console.log(path);
        legacy(path, output + path.replace(/\.[^.]*$/, ".html"));
      });
    });
  } else {
    legacy(filename, output);
  }
});

